### ISSUE TITLE
[Feature Request] Integration test snippet

### ISSUE THREAD

**Issue by EelcoLos** [FastEndpoints/VSCode-Extension#1]
I do like the concept of the snippets.

Could the integration test also be included?

**Comment by dj-nitehawk** [comment]
@drilko will you be able to port these 3 snippets to the vscode extension?

https://github.com/FastEndpoints/Visual-Studio-Extension/blob/e6117ceda58358da8e5cbe2dcc638c729142576b/FastEndpoints/FastEndpoints.snippet#L650-L756

**Comment by drilko** [comment]
@dj-nitehawk sure thing, I'm tight with time currently. Will try by EOD saturday.

**Comment by drilko** [comment]
@dj-nitehawk @EelcoLos Requested snippets are up. Please upgrade the extension version to check it out :)
